### ISSUE TITLE
ShinyLearner GUI Expands '~' Incorrectly For Input Directory

### ISSUE THREAD

**Issue by definitelysean** [srp33/ShinyLearner#4]
When using the ShinyLearner Shiny app to generate ShinyLearner commands, providing a path such as '~/etc/sample_data.csv' substitutes '/home/tjlee3' for ~. This is probably because the Shiny app is running as user tjlee3 on the host, as specified in this config file: 

https://github.com/srp33/ShinyLearner/blob/69dc4b7861ba88c7df96f570496d11cb8d7d1375/gui/server_config/shiny-server.conf

~ probably shouldn't be transformed by the application. If the users are pasting the resulting command into bash, bash can take care of resolving the current user's home directory.

**Comment by srp33** [comment]
Sean, thanks for the tip. We'll address that as soon as possible!

**Comment by srp33** [comment]
@definitelysean I believe we resolved this. Will you please test it and let us know if it's working for you?

**Comment by definitelysean** [comment]
@srp33 Looks good! :+1:
